<?php
/** @var \AHT\Question\Block\Template $block */
?>
<?php

$item = $block->getQuestions();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;

?>
    <div class="block question-list" id="customer-questions">
        <div class="block-content">
            <ol class="items question-items">
                <?php foreach ($item as $question) : ?>
                    <div <?php echo 'class="question-answer-' . $question->getQuestionId().'"' ?> >
                        <li <?php echo 'class="item question-item-' . $question->getQuestionId().'"' ?> <?php echo 'id="'.$question->getQuestionId().'"'?>  itemscope itemprop="question" itemtype="">
                        <h3 class="product-name">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($block->getProductById($question->getProductId()))) ?>"><?= $block->getProductById($question->getProductId())->getName() ?></a>
                        </h3>
                            <div class="question-details">
                                <p class="question-author">
                                    <span class="question-details-label"><?= $block->escapeHtml(__('Questioned by: ')) ?></span>
                                    <strong class="question-details-value" itemprop="author"><?= $block->escapeHtml($question->getName()) ?></strong>
                                </p>
                                <p class="question-date">
                                    <span class="question-details-label"><?= $block->escapeHtml(__('Posted on: ')) ?></span>
                                    <time class="question-details-value" itemprop="datePublished" datetime="<?= $block->escapeHtmlAttr($block->formatDate($question->getCreatedAt(), $format)) ?>"><?= $block->escapeHtml($block->formatDate($question->getCreatedAt(), $format)) ?></time>
                                </p>
                            </div>
                            <div class="question-title" itemprop="name"><h3><?= $block->escapeHtml('Question: ' . $question->getQuestion()) ?></h3></div>
                                                       
                            <div class="question-content" itemprop="description">
                                <?= /* @noEscape */ nl2br($block->escapeHtml('The answer of Admin: ' . $question->getAdminAnswer())) ?>
                            </div> 

                            <?php
                            $answer = $block->getAnswers($question->getProductId());
                            foreach($answer->getData() as $temp) : ?>
                                <?php if ($temp['question_id']==$question->getQuestionId()) : ?>
                                    <div class="question-content" itemprop="description">
                                        <?= /* @noEscape */ nl2br($block->escapeHtml('Answer of ' .$temp['user_name'] .': ' . $temp['answer_content'])) ?>
                                    </div> 
                                <?php endif ?>
                            <?php endforeach; ?>
                        </li>
                    </div>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>

    <script>
    require([
        'jquery',
        'slick'
    ], function($) {
        $(document).ready(function() {
            $(".question-items").slick({
                dots: false,
                infinite: false,
                arrows: false,
                slidesToShow: <?= $block->getData('number_show') ?>,
                //slidesToScroll: 2,
                responsive: [{
                        breakpoint: 780,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2,
                            rows: 2,
                        }
                    },
                ]
            });

            $("li.item").each(function(){
            var count = $(this).children('div.question-content').length;
            $(this).children('div.question-content:gt(2)').hide();
            if (count>3) {
                $(this).append('<a style="cursor: pointer;" class="loadMore">Show More Answers</a>');
            }
            else {
                $(this).append('<a style="cursor: pointer; display: none" class="loadMore">Show More Answers</a>');
            }
        });

        $(".loadMore").click(function(e){
            e.preventDefault();
            formTest = "." + e.target.parentElement.parentElement.className;
            show = formTest.slice(17);
            strAnswer = 'li.question-item-' + show;
            countItem =  $(this).parent(strAnswer).children('div.question-content').length;  	
            countAnswer = 3;
            $(strAnswer).on("click",'.loadMore',function (){
                if(countAnswer <= countItem) {
                        countAnswer += 3;
                        temp = 'div.question-content:lt(' + countAnswer + ')';
                        $(this).parent(strAnswer).children(temp).show();  	
                    }	
                else {
                    $(this).removeClass('loadMore').addClass('loadLess').text('Show Less Answers'); 
                }
                });
            $(strAnswer).on("click",'.loadLess',function (){
                $(this).parent(strAnswer).children('div.question-content:gt(2)').hide();
                $(this).removeClass('loadLess').addClass('loadMore').text('Show More Answers'); 
            });
        });
        });
    });
</script>