<?php $value = $block->getEditRecord();

?>
<form method='POST' action="<?php echo $block->getBaseUrl() ?>crud/index/save">
  <div class="form-group">
    <label for="name">Name:</label>
    <input type="text" class="form-control" id="name" value="<?=(isset($value)) ? $value->getName() : ""?>" name="name">
  </div>
  <div class="form-group">
    <label for="post_content">post content:</label>
    <input type="text" class="form-control" value="<?=(isset($value)) ? $value->getPost_content() : ""?>" id="post_content" name="post_content">
  </div>
  <button type="submit" class="btn btn-default" name="edit" >Save</button>
</form>














































