<form method='POST' action="<?php echo $block->getBaseUrl() ?>crud/index/save">
  <div class="form-group">
    <label for="name">Name:</label>
    <input type="text" class="form-control" id="name" value="" name="name">
  </div>
  <div class="form-group">
    <label for="post_content">post content:</label>
    <input type="text" class="form-control" value="" id="post_content" name="post_content">
  </div>
  <button type="submit" class="btn btn-default" name="create" >Save</button>
</form>












