<?php
/** @var \AHT\QA\Block\Product\ListQuestion $block */
?>

<?php

$item = $block->getQuestions();
$answer = $block->getAnswers();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;

?>
<?php if (count($item)) : ?>
    <div class="block question-list" id="customer-questions">
        <div class="block-content">
            <ol class="items question-items">
                <?php foreach ($item as $question) : ?>
                    <div <?php echo 'class="question-answer-' . $question->getQuestionId().'"' ?> >
                        <li <?php echo 'class="item question-item-' . $question->getQuestionId().'"' ?> <?php echo 'id="'.$question->getQuestionId().'"'?>  itemscope itemprop="question" itemtype="">
                            <div class="question-details">
                                <p class="question-author">
                                    <span class="question-details-label"><?= $block->escapeHtml(__('Questioned by: ')) ?></span>
                                    <strong class="question-details-value" itemprop="author"><?= $block->escapeHtml($question->getName()) ?></strong>
                                </p>
                                <p class="question-date">
                                    <span class="question-details-label"><?= $block->escapeHtml(__('Posted on: ')) ?></span>
                                    <time class="question-details-value" itemprop="datePublished" datetime="<?= $block->escapeHtmlAttr($block->formatDate($question->getCreatedAt(), $format)) ?>"><?= $block->escapeHtml($block->formatDate($question->getCreatedAt(), $format)) ?></time>
                                </p>
                            </div>
                            <div class="question-title" itemprop="name"><h3><?= $block->escapeHtml('Question: ' . $question->getQuestion()) ?></h3></div>
                                                       
                            <div class="question-content admin-answer" itemprop="description">
                                <?= /* @noEscape */ nl2br($block->escapeHtml('The answer of Admin: ' . $question->getAdminAnswer())) ?>
                            </div> 

                            <?php foreach($answer->getData() as $temp) : ?>
                                <?php if ($temp['question_id']==$question->getQuestionId()) : ?>
                                    <div class="question-content" itemprop="description">
                                        <?= /* @noEscape */ nl2br($block->escapeHtml('Answer of ' .$temp['user_name'] .': ' . $temp['answer_content'])) ?>
                                    </div> 
                                <?php endif ?>
                            <?php endforeach; ?>
                        </li>
                        <button class="answer-button">Reply</button>
                    </div>
                   
                            <form <?php echo 'name="saveAnswer-' . $question->getQuestionId().'"' ?>   method="post"  style="display: none;"  class="other-answer-form">
                                <div class="question-content" itemprop="description">
                                    <h4>Do you want to answer this question?</h4>
                                    <?= /* @noEscape */ nl2br($block->escapeHtml('Your Name:  ')) ?>
                                    <input required style="max-width: 300px" placeholder="Your Name Want To Show..." name="user_name" type="text" class="name_answer"> <br>
                                    <?= /* @noEscape */ nl2br($block->escapeHtml('Your Answer: ')) ?>
                                    <input required style="max-width: 300px" placeholder="Your Answer..." name="answer" type="text" class="content_answer">
                                    <input hidden type="text" name="question_id" value="<?= $question->getQuestionId()?>" />
                                    <button  name="submit" type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Answer')) ?></span></button>
                                </div> 
                            </form>
                    
                            <hr>
                <?php endforeach; ?>
            </ol>
            <?php if ($item->getSize() > 10) : ?>
                <div class="toolbar question-toolbar">
                    <?= $block->getChildHtml('toolbar') ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>


<script>
require(['jquery'],function($){
    jQuery(document).ready(function() {
        var form;
        var saveAnswer;
        var conntItem;
        jQuery(".answer-button").click(function(e){
            e.preventDefault();
            formName = "." + e.target.parentElement.className;
            form = formName.slice(17);
            saveAnswer = 'form[name ="saveAnswer-' + form + '"]';
            $(saveAnswer).toggle("slow", "swing");
        });

        jQuery("li.item").each(function(){
            var count = jQuery(this).children('div.question-content').length;
            jQuery(this).children('div.question-content:gt(2)').hide();
            if (count>3) {
                jQuery(this).append('<a style="cursor: pointer;" class="loadMore">Show More Answers</a>');
            }
            else {
                jQuery(this).append('<a style="cursor: pointer; display: none" class="loadMore">Show More Answers</a>');
            }
        });

        jQuery(".loadMore").click(function(e){
            e.preventDefault();
            formTest = "." + e.target.parentElement.parentElement.className;
            show = formTest.slice(17);
            strAnswer = 'li.question-item-' + show;
            countItem =  jQuery(this).parent(strAnswer).children('div.question-content').length;  	
            countAnswer = 3;
            jQuery(strAnswer).on("click",'.loadMore',function (){
                if(countAnswer <= countItem) {
                        countAnswer += 3;
                        temp = 'div.question-content:lt(' + countAnswer + ')';
                        jQuery(this).parent(strAnswer).children(temp).show(500);  	
                    }	
                else {
                    jQuery(this).removeClass('loadMore').addClass('loadLess').text('Show Less Answers'); 
                }
                });
            jQuery(strAnswer).on("click",'.loadLess',function (){
                jQuery(this).parent(strAnswer).children('div.question-content:gt(2)').hide(500);
                jQuery(this).removeClass('loadLess').addClass('loadMore').text('Show More Answers'); 
            });
        });

        jQuery(".other-answer-form").submit(function(e){
            e.preventDefault();
            var name = e.target[0].value;
            var answer = e.target[1].value;
            var question_id = e.target[2].value;
            var url = "<?php echo $block->getBaseUrl() . 'question/product/answerquestion' ?>";

            jQuery.ajax({
            url: url,
            type: "POST",
            data: {
                answer:answer, 
                user_name:name, 
                question_id:question_id
            },
            showLoader: true,
            cache: false,
            success: function(response){
                $(saveAnswer).trigger("reset");
                var data = jQuery.parseJSON(response);
                var html = '<div class="question-content" itemprop="description">';
                html += 'Answer of ' + data.user_name  + ': ' + data.answer_content;
                html += '</div>';
                answerClass = ".question-item-" + data.question_id;
                $(answerClass + " .admin-answer").after(html);
            },
            error: function (xhr, status, errorThrown) {
                console.log('Error happens. Try again.');
            }
        },
        );
        });
    });
});
</script>